### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by FUCKTHEATTITUDE**

### CODE REVIEW

**Comment by Sangwan5688** [comment]
All this requirements aren't actually required.

**Comment by FUCKTHEATTITUDE** [comment]
Can you help me to deploy in heruko server

**Comment by Sangwan5688** [comment]
Heroku is no longer free, so this code doesn't work anymore

**Comment by FUCKTHEATTITUDE** [comment]
I am having heruko acnt so that i am asked you ,if you can help means stop
replying

**Pull request closed without merging**
